---
# POD
apiVersion: v1
kind: Pod
metadata:
  namespace: simplewp
  name: db
  labels:
    name: db
spec:
  containers:
  - name: db
    image: mariadb:10.6.4-focal
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: somewordpress
      - name: MYSQL_DATABASE
        value: wordpress
      - name: MYSQL_USER
        value: wordpress
      - name: MYSQL_PASSWORD
        value: wordpress
---
# SVC
apiVersion: v1
kind: Service
metadata:
  namespace: simplewp
  name: db
spec:
  selector:
    name: db
  type: ClusterIP
  ports:
  - port: 3306 # service port 
    targetPort: 3306 # port on the pod 
