# POD
apiVersion: v1
kind: Pod
metadata:
  namespace: simplewp
  name: wp
  labels:
    name: wp
spec:
  containers:
  - name: wp
    image: wordpress:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: WORDPRESS_DB_HOST
        value: db
      - name: WORDPRESS_DB_USER
        value: wordpress
      - name: WORDPRESS_DB_PASSWORD
        value: wordpress
      - name: WORDPRESS_DB_NAME
        value: wordpress
---
# SVC
apiVersion: v1
kind: Service
metadata:
  namespace: simplewp
  name: wp
spec:
  selector:
    name: wp
  type: ClusterIP
  ports:
  - port: 80 # service port 
    targetPort: 80 # port on the pod 
---
# INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: simplewp
  name: wp
  labels:
    name: wp
spec:
  rules:
  - host: wordpress.kube
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wp
            port: 
              number: 80
