apiVersion: v1
kind: Service
metadata:
  namespace: whoami
  name: whoami
spec:
  selector:
    name: whoami
  type: ClusterIP
  ports:
  - port: 80 # service port 
    targetPort: 80 # port on the pod 
